server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: NOTIFICATION-SERVICE
          uri: http://localhost:8089/
          predicates:
            - Path=/notification/**
        - id: user-service
          uri: http://localhost:9002/
          predicates:
            - Path=/api/users/**
        - id: answer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/answers/**
        - id: Questions-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/questions/**
        - id: Voting
          uri: http://localhost:8082/
          predicates:
            - Path=/api/voting/**
        - id: Auth-Service
          uri: http://localhost:9001/
          predicates:
            - Path=/api/**