apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  labels:
    name: cassandra-service
    app: user-service
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    name: cassandra-pod
    app: cassandra-pod








