apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
    app: user-service
spec:
  type: LoadBalancer
  ports:
  - port: 9002
    targetPort: 9002
  selector:
    name: user-service-pod
    app: user-service








