apiVersion: v1
kind: Pod
metadata:
  name: user-service-pod
  labels:
    name: user-service-pod
    app: user-service-pod
spec:
  containers:
  - name: user-service
    image: 212729/user-service-image:latest
    ports:
      - containerPort: 9002







