apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-deployment
  template:
    metadata:
      labels:
        app: user-service-deployment
    spec:
      containers:
        - name: user-service-deployment
          image: 212729/user-service-image:latest
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service-deployment
#  type: ClusterIp
  ports:
      port: 80
      targetPort: 9002







