spring:
  kafka:
    bootstrap-servers: ${KafkaHost}:${KafkaPort}
  data:
    cassandra:
      port: ${DBPort}
      contact-points: ${DBHost}
      keyspace-name: userKeySpace
      schema-action: create_if_not_exists
server:
  port : 9002
  error:
    include-message: always



