spring:
  kafka:
#    bootstrap-servers: host.docker.internal
    bootstrap-servers: localhost:9092
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
#      keyspace-name: userKeySpace
#      entity-base-package: com.SWAFinalProject.userservice.entity
#      schema-action: create_if_not_exists
server:
  port : 9002
  error:
    include-message: always



