spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: mykeyspace
      entity-base-package: com.SWAFinalProject.userservice.entity
      schema-action: create_if_not_exists



