app:
  answer_service: http://localhost:8080/api/v1/answers
  jwtSecret: very-secret
spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    cassandra:
      port: 9042
      contact-points: myqcassandra
      keyspace-name: myqkeyspace
      entity-base-package: com.finalproject.questionsservice.Entity
      schema-action: create_if_not_exists

server:
  port: 8089



