spring:
#  kafka:
#    bootstrap-servers: localhost:9094
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: mykeyspace
      entity-base-package: com.Voting.Voting.entity
      schema-action: create_if_not_exists
server:
  port : 9004
