apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification-service
  labels:
    app: email-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app : email-notification-service
  template:
    metadata:
      labels:
        app: email-notification-service
    spec:
      containers:
        - name: email-notification-service
          image: email-notification-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8089

---

kind: Service
apiVersion: v1
metadata:
  name:  email-notification-service-svc
spec:
  selector:
    app:  email-notification-service
  ports:
    - port:  80
      targetPort:  8089